### ISSUE TITLE
SASL_SSL protected kafka cluster

### ISSUE THREAD

**Issue by jrevillard** [muralibasani/kafkawizeclusterapi#9]
Hi,

I would like to test your tool but we have a SASL_SSL protected kafka cluster. Would it be possible to add this protocol ? (also, as far as SASL is concerned, we are using kerberos authentication so GSSAPI).

Best,
Jerome

**Comment by muralibasani** [comment]
Hi Jerome, thank you for asking. I have SASL_SSL protocol (for PLAIN and GSSAPI) enabled in the Pro version of Kafkawize. 
Please visit https://kafkawize.com for all available features in **Pro** version.. Would be great, if you can [Request for Demo](https://kafkawize.com/request-for-demo/), I would be happy to set it up next week.
